# LibreLane configuration file

DESIGN_NAME: heichips25_pudding
VERILOG_FILES: 
- dir::../src/heichips25_pudding.sv
- dir::../src/dac128module.v
- dir::../src/inverterpair.sv

CLOCK_PORT: clk
CLOCK_PERIOD: 10 # 10ns = 100MHz

# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6

# Absolute die size
FP_SIZING: absolute
PL_TARGET_DENSITY_PCT: 70

# Small DEF template
DIE_AREA: [0, 0, 500, 200]
FP_DEF_TEMPLATE: dir::def/heichips25_template_small.def

# Large DEF template
#DIE_AREA: [0, 0, 500, 415]
#FP_DEF_TEMPLATE: dir::def/heichips25_template_large.def

# Use Leo's special PDN configuration file
PDN_CFG: dir::pdn_cfg.tcl

# Don't use power rings or TopMetal2 layer
#PDN_MULTILAYER: false
PDN_MULTILAYER: true
RT_MAX_LAYER: TopMetal1
PDN_VPITCH: 20
PDN_HPITCH: 20

PNR_SDC_FILE: dir::constraints/pudding_min.sdc
SIGNOFF_SDC_FILE: dir::constraints/pudding_min.sdc

# Enable for better SystemVerilog support
USE_SLANG: true

# reserve space for the logo
FP_OBSTRUCTIONS: 
- [355, 48, 500, 77]
- [355, 128, 500, 157]

MACROS:
  dac128module:
    gds:
      - dir::../gds/dac128module.gds
    lef:
      - dir::../gds/dac128module.lef
#   nl:
#     - dir::../src/dac128module.sv
    instances:
      dacL:
        location: [360, 50]
        orientation: N
      dacH:
        location: [360, 130]
        orientation: N

# Connect macro power pins to the PDN
PDN_CONNECT_MACROS_TO_GRID: true

# Denser grid so a strap is always near the pins
#PDN_HPITCH: 20
#PDN_VPITCH: 20

# Nudge straps so they actually cross the pin rectangles
#PDN_HOFFSET: 10
#PDN_VOFFSET: 10

#PDN_HWIDTH: 2
#PDN_VWIDTH: 2

PDN_MACRO_CONNECTIONS:
  - "dacL VPWR VGND VDD VSS"
  - "dacH VPWR VGND VDD VSS"

